import { FileText, Download, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { AnalysisResult } from "@/types/analysis";
import { useState } from "react";

interface ReportGeneratorProps {
  result: AnalysisResult;
}

export function ReportGenerator({ result }: ReportGeneratorProps) {
  const [isGenerating, setIsGenerating] = useState(false);

  const generateReport = async () => {
    setIsGenerating(true);
    
    // Simulate PDF generation delay
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    // Create report content
    const reportContent = `
AI DeepFke Detection System
=====================================
Detect Manipulated Images,Videos,Audios and Url's

Case ID: ${result.id}
Generated: ${new Date().toLocaleString('en-IN', { dateStyle: 'full', timeStyle: 'long' })}

EVIDENCE DETAILS
----------------
File Name: ${result.fileName}
File Type: ${result.fileType.toUpperCase()}
File Size: ${(result.fileSize / 1024 / 1024).toFixed(2)} MB
File Hash (SHA-256): ${result.fileHash}

ANALYSIS VERDICT
----------------
Result: ${result.verdict.toUpperCase()}
Confidence Score: ${(result.confidenceScore * 100).toFixed(1)}%

AI EXPLANATION
--------------
${result.explanation}

TECHNICAL DETAILS
-----------------
Model Used: ${result.technicalDetails.modelUsed}
Processing Time: ${result.technicalDetails.processingTime}ms
Checks Performed:
${result.technicalDetails.checksPerformed.map(c => `  - ${c}`).join('\n')}

DETECTED ANOMALIES
------------------
${result.technicalDetails.anomalies.length === 0 
  ? 'No significant anomalies detected.'
  : result.technicalDetails.anomalies.map(a => 
    `- ${a.type} (${a.severity.toUpperCase()})\n  Location: ${a.location || 'N/A'}\n  Description: ${a.description}\n  Confidence: ${(a.confidence * 100).toFixed(1)}%`
  ).join('\n\n')
}

${result.exifData ? `
EXIF METADATA
-------------
${Object.entries(result.exifData)
  .filter(([_, v]) => v !== undefined)
  .map(([k, v]) => `${k}: ${v}`)
  .join('\n')
}
` : ''}

DISCLAIMER
----------
This report is generated by an AI-powered analysis system.
Results should be verified by qualified forensic experts before use
in legal proceedings. This analysis is provided as investigative
support only.

=====================================
AI DeepFake Detection System

    `.trim();

    // Create and download the file
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `DeepGuard_Report_${result.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setIsGenerating(false);
  };

  return (
    <div className="glass-panel p-4">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-sm font-semibold text-foreground flex items-center gap-2">
          <FileText className="w-4 h-4 text-primary" />
          Police Case Report
        </h3>
      </div>

      <div className="p-4 rounded-lg bg-secondary/50 border border-border mb-4">
        <div className="grid grid-cols-2 gap-4 text-sm">
          <div>
            <p className="text-xs text-muted-foreground mb-1">Case ID</p>
            <p className="font-mono text-foreground">{result.id}</p>
          </div>
          <div>
            <p className="text-xs text-muted-foreground mb-1">File Hash</p>
            <p className="font-mono text-foreground truncate" title={result.fileHash}>
              {result.fileHash.slice(0, 16)}...
            </p>
          </div>
          <div>
            <p className="text-xs text-muted-foreground mb-1">Verdict</p>
            <p className={`font-semibold ${
              result.verdict === 'safe' ? 'text-success' :
              result.verdict === 'warning' ? 'text-warning' : 'text-destructive'
            }`}>
              {result.verdict.toUpperCase()}
            </p>
          </div>
          <div>
            <p className="text-xs text-muted-foreground mb-1">Confidence</p>
            <p className="font-mono text-foreground">
              {(result.confidenceScore * 100).toFixed(1)}%
            </p>
          </div>
        </div>
      </div>

      <Button 
        onClick={generateReport} 
        disabled={isGenerating}
        className="w-full"
        variant="forensic"
      >
        {isGenerating ? (
          <>
            <Loader2 className="w-4 h-4 animate-spin" />
            Generating Report...
          </>
        ) : (
          <>
            <Download className="w-4 h-4" />
            Export Case Report
          </>
        )}
      </Button>
    </div>
  );
}
